## import modules

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
dataset = datasets.load_breast_cancer()
X = dataset.data
y = dataset.target

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)
#concatenate features and labels
y_train = np.reshape(y_train,(y_train.shape[0],1))
training_data = np.concatenate((X_train,y_train),axis=1)

y_test = np.reshape(y_test,(y_test.shape[0],1))
testing_data = np.concatenate((X_test,y_test),axis=1)

print(training_data.shape)

(455, 31)


## encode data

In [4]:
from random_forest import encode_data
training_data = encode_data(training_data)
print(training_data[0])
len(training_data[0])

[149, 164, 200, 171, 377, 380, 173, 269, 134, 362, 308, 221, 306, 276, 114, 247, 90, 245, 186, 226, 187, 176, 232, 214, 244, 287, 113, 213, 125, 307, 1]


31

## questions

In [5]:
from decision_tree import Question
print(training_data[0])
# let's write a question for a numeric question
q=Question(1,165)
example = training_data[0]
q.match(example)  #this will be false since forth example diameter is less than 3

[149, 164, 200, 171, 377, 380, 173, 269, 134, 362, 308, 221, 306, 276, 114, 247, 90, 245, 186, 226, 187, 176, 232, 214, 244, 287, 113, 213, 125, 307, 1]


False

## partition

In [6]:
from decision_tree import partition
print(type(training_data))
#demonstrate training data whether first categorical value is >=1
true_rows, false_rows = partition(training_data, Question(0,149))
len(true_rows),len(false_rows)

<class 'list'>


(262, 193)

## Gini impurity

In [7]:
from decision_tree import gini
print(gini(training_data))

0.4646395362878879


## information gains

In [9]:
from decision_tree import info_gain
current_impurity = gini(training_data)
print("current gini impurity is: ", current_impurity)

datasets = np.array(training_data)
# true_rows,false_rows = partition(data_set, Question(0,0))
# info_gain(true_rows,false_rows,current_impurity)
# datasets[0,1]
for data in datasets[:,1]:
    # print(data)
    true_rows,false_rows = partition(training_data, Question(1,data))
    print(info_gain(true_rows,false_rows,current_impurity))

current gini impurity is:  0.4646395362878879
0.07714980089239323
0.03832109136862977
0.07318252580809284
0.018640303712951056
0.08437409284218239
0.10054240415173135
0.060494411161275845
0.06938678903514059
0.06881357461700133
0.03726166421375242
0.0842163502305725
0.05457784928162702
0.07578741537499573
0.06329671435010031
0.07907822439737891
0.005510204081632608
0.047237129171195213
0.05457784928162702
0.002601574249925853
0.031108964295777423
0.08913924979004015
0.0707077065086757
0.07714980089239323
0.00017974665488817987
0.0924838217506112
0.04323213530322495
0.07714980089239323
0.0026750232595451062
0.10279865847568548
0.050100473045654625
0.09272838542324857
0.06301708394474992
0.017195203754636124
0.019375402830983497
0.02786043449637919
0.06338364931771517
0.0680266814740701
0.04922257597888769
0.006070787963041946
0.04200037987492667
0.08637609759891732
0.007119247188651423
0.08678616142212536
0.08769810854000848
0.0011917746100377768
0.09563335872139891
0.052769194184987635

## find best split

In [8]:
from decision_tree import find_best_split
best_gain, best_question = find_best_split(training_data)
print(best_gain, best_question.column, best_question.value)

0.3301640450017654 27 256


In [15]:
from decision_tree import build_tree
from decision_tree import print_tree
mode_1 = build_tree(training_data)
print_tree(mode_1)

question is: 
27 256
--> True:
question is: 
23 228
--> True:
question is: 
13 114
--> True:
question is: 
26 203
--> True:
leaf
(array([0]), array([140]))
--> false:
leaf
(array([1]), array([1]))
--> false:
question is: 
29 351
--> True:
leaf
(array([0]), array([1]))
--> false:
leaf
(array([1]), array([2]))
--> false:
question is: 
24 343
--> True:
leaf
(array([0]), array([3]))
--> false:
leaf
(array([1]), array([7]))
--> false:
question is: 
23 314
--> True:
question is: 
27 170
--> True:
leaf
(array([0]), array([15]))
--> false:
question is: 
29 37
--> True:
leaf
(array([0]), array([1]))
--> false:
leaf
(array([1]), array([3]))
--> false:
question is: 
29 2
--> True:
question is: 
22 254
--> True:
question is: 
24 199
--> True:
leaf
(array([0]), array([3]))
--> false:
question is: 
17 351
--> True:
leaf
(array([0]), array([2]))
--> false:
leaf
(array([1]), array([22]))
--> false:
question is: 
21 366
--> True:
question is: 
21 375
--> True:
leaf
(array([1]), array([17]))
--> false:


In [16]:
from decision_tree import classify
correct = 0
wrong = 0
for row in testing_data:
    if row[-1] == classify(row, mode_1):
        correct += 1
    else:
        wrong += 1
print(correct,wrong)

63 51


In [10]:
from random_forest import training_model
from random_forest import predict
import random
model = training_model(training_data, 100)
predict(testing_data, model, 100)
# _size = len(training_data)
# sample = random.sample(training_data,int(_size/5))
# len(sample)

(0, 114)